#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase

wclean Add-On/pulseTotalPressure 

rm InletOutletFlowRate.dat

#------------------------------------------------------------------------------
